name: GoCI

on:
  push:
    branches: [ master ]
    paths: [ 'backend/**' ]
  pull_request:
    branches: [ master ]
    paths: [ 'backend/**' ]

defaults:
  run:
    working-directory: backend

jobs:
  golint:
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo $PWD
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.33.0

  gobuild:
    name: Go Build
    needs: golint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo $PWD

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Build
      run: go build -v -race ./...

    - name: Test
      run: go test -v ./...
